name: rainbow
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bwa=0.7
  - bedtools
  - graphviz=2.38
  - samtools=1.6
  - picard=2
  - gatk4
  - pytabix
  - snpeff=4.3
  - python=3
  - pysam=0.13
  - bitarray=0.8
  - pyyaml=3.11
  - igv=2.3 
  - snakemake
